# This is the configuration file for the MPP application
outPaths:
  modelPoints: C:/appData/PLAI_CAM_DCS_v5_20240603/outputs/v1

sysPaths:
  enums: inputs/enums

tablePaths:
  - inputs/tables
  - inputs/tables/subfolder1
  - inputs/tables/subfolder2

dataPaths:
  - C:/appData/PLAI_CAM_DCS_v5_20240603/inputs/data/I17_FULL


data:
  - U_BELD.IF_
  - U_BELR.IF_
  - U_CAPR.IF_
  - U_HBD2.IF_
  - U_HBR2.IF_
  - U_HNWD.IF_
  - U_HNWR.IF_
  - U_HYBD.IF_
  - U_HYBR.IF_
  - U_PAAD.IF_
  - U_PAAR.IF_
  - U_PFPR.IF_
  - U_PFR2.IF_
  - U_PFR3.IF_
  - U_PFR4.IF_
  - U_PFR5.IF_
  - U_PFR6.IF_
  - U_PFR7.IF_
  - U_PFR8.IF_
  - U_PIAD.IF_
  - U_PIAR.IF_
  - U_RBEL.IF_
  - UBELDR.IF_
  - UBELRR.IF_
  - UEGBF2.IF_
  - UEGBF3.IF_
  - UEGBR2.IF_
  - UEGBR3.IF_
  - UEGBR4.IF_
  - UEGBR5.IF_
  - UEGBR6.IF_
  - UEGBRF.IF_
  - UEGBRR.IF_
  - UENGRF.IF_
  - UENGRR.IF_
  - UEPAAD.IF_
  - UEPAD0.IF_
  - UEPAD2.IF_
  - UEPAD3.IF_
  - UEPAD4.IF_
  - UEPAD5.IF_
  - UEPAD6.IF_
  - UEPAD7.IF_
  - UEPAD8.IF_
  - UEPAR0.IF_
  - UEPAR1.IF_
  - UEPAR2.IF_
  - UEPAR3.IF_
  - UEPAR4.IF_
  - UEPAR5.IF_
  - UEPAR6.IF_
  - UEPAR7.IF_
  - UEPAR8.IF_
  - UEPAR9.IF_
  - UEPAXR.IF_
  - UEPD11.IF_
  - UEPD12.IF_
  - UEPD14.IF_
  - UEPEPR.IF_
  - UEPMC1.IF_
  - UEPMC2.IF_
  - UEPMC3.IF_
  - UEPMC4.IF_
  - UEPMC5.IF_
  - UEPMC6.IF_
  - UEPMC7.IF_
  - UEPMC8.IF_
  - UEPMC9.IF_
  - UEPMIR.IF_
  - UEPR10.IF_
  - UEPR11.IF_
  - UEPR12.IF_
  - UEPR13.IF_
  - UEPR14.IF_
  - UEPR15.IF_
  - UEPR16.IF_
  - UEPR17.IF_
  - UEPR18.IF_
  - UEPR19.IF_
  - UEPR20.IF_
  - UEPR21.IF_
  - UEPR22.IF_
  - UEPR23.IF_
  - UEPR24.IF_
  - UEPR25.IF_
  - UEPR26.IF_
  - UEPR27.IF_
  - UEPR28.IF_
  - UEPR29.IF_
  - UEPRD1.IF_
  - UEPRD2.IF_
  - UEPRD3.IF_
  - UEPRD4.IF_
  - UEPRD5.IF_
  - UEPRD6.IF_
  - UEPRD7.IF_
  - UEPRD8.IF_
  - UEPRR1.IF_
  - UEPRR2.IF_
  - UEPRR3.IF_
  - UEPRR4.IF_
  - UEPRR5.IF_
  - UGFPAR.IF_
  - UGPAAR.IF_
  - UGPAR2.IF_
  - UGPAR3.IF_
  - UGPAR4.IF_
  - UGPAR5.IF_
  - UGPAR6.IF_
  - UGPAR7.IF_
  - UGPAR8.IF_
  - UGPAR9.IF_
  - UGPR10.IF_
  - UGPRR1.IF_
  - UGPRR2.IF_
  - UGPRR3.IF_
  - UGPRR4.IF_
  - UGPRR5.IF_
  - UGPRR6.IF_
  - ULPAAR.IF_
  - UPMC10.IF_
  - UPMC11.IF_
  - UPMC12.IF_
  - URBELP.IF_
  - URBISF.IF_
  - URBLPD.IF_
  - URPIAD.IF_
  - URPIAR.IF_
  - URTISF.IF_
  - UTBELD.IF_
  - UTBELR.IF_
  - UTCAPR.IF_
  - UTPIAD.IF_
  - UTPIAR.IF_


tableMaps:
  campaign_gio_2: CAMPAIGN_GIO_2.fac
  campaign_xsa: CAMPAIGN_XSA.fac
  dedn_disc: DEDN_DISC.fac
  dedn_lbu: DEDN_LBU.fac
  param_dcs: PARAM_DCS.fac
  part_surr_idx: PART_SURR_IDX.fac
  premium_counter: PREMIUM_COUNTER.fac
  rider_cc_index: RIDER_CC_INDEX.fac
  rider_max: RIDER_MAX.fac
  rider_med_index: RIDER_MED_INDEX.fac
  rider_medical_ben2: RIDER_MEDICAL_BEN2.fac
  rider_pep_index: RIDER_PEP_INDEX.fac
  rider_prenatal_ben: RIDER_PRENATAL_BEN.fac
  rider_pwaiv1_method1: RIDER_PWAIV1_METHOD1.fac
  rider_pwaiv2_method1: RIDER_PWAIV2_METHOD1.fac
  rider_sel: RIDER_SEL.fac
  rider_sel_gio: RIDER_SEL_GIO.fac
  rider_sp_index: RIDER_SP_INDEX.fac
  rider_wp_index: RIDER_WP_INDEX.fac

enums:
  - ridRiTreaty
  - ridRiIcg
  - benCode
  - ifrsCcfExternal

enumNames:
  ridRiTreaty: inputs/enums/RID_RI_TREATY.csv
  ridRiIcg: inputs/enums/RID_RI_ICG.csv
  benCode: inputs/enums/BEN_CODE.csv
  ifrsCcfExternal: inputs/enums/IFRS_CCF_EXTERNAL.csv

